steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/subba-personal-project/node:v1.0', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/subba-personal-project/node:v1.0']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'node-app', '--image', 'gcr.io/subba-personal-project/IMAGE', '--region', 'us-central1']
images:
- gcr.io/subba-personal-project/node:v1.0
- logsBucket: 'gs://subba-appengine'